### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mixermat99** [DantSu/PrinterThermal-ESCPOS-Android#20]
Hi, im using your library and your code to print with an pos printer but i have this issue:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.silentprint, PID: 20914
    java.lang.ArrayIndexOutOfBoundsException: length=0; index=4
        at com.dantsu.printerthermal_escpos_bluetooth.textparser.PrinterTextParserImg.<init>(PrinterTextParserImg.java:105)
        at com.dantsu.printerthermal_escpos_bluetooth.textparser.PrinterTextParserColumn.appendImage(PrinterTextParserColumn.java:242)
        at com.dantsu.printerthermal_escpos_bluetooth.textparser.PrinterTextParserColumn.<init>(PrinterTextParserColumn.java:66)
        at com.dantsu.printerthermal_escpos_bluetooth.textparser.PrinterTextParserLine.<init>(PrinterTextParserLine.java:42)
        at com.dantsu.printerthermal_escpos_bluetooth.textparser.PrinterTextParser.parse(PrinterTextParser.java:162)
        at com.dantsu.printerthermal_escpos_bluetooth.Printer.printFormattedText(Printer.java:132)
        at com.example.silentprint.MainActivity.printIt(MainActivity.java:39)
        at com.example.silentprint.MainActivity$1.onClick(MainActivity.java:29)
        at android.view.View.performClick(View.java:7870)
        at android.widget.TextView.performClick(TextView.java:14970)
        at android.view.View.performClickInternal(View.java:7839)
        at android.view.View.access$3600(View.java:886)
        at android.view.View$PerformClick.run(View.java:29363)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7860)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

**Comment by DantSu** [comment]
<image> tag can't be empty.
